version: "3"

services:

  #Databse Service
  database:
    image: postgres
    container_name: database_postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USERNAME=postgres
      - POSTGRES_DB=dbFastFeet
    ports:
      - "5432:5432"
    volumes:
      - "postgres:/postgres/data"

volumes:
  postgres:
